package mapping;
// Generated 6 kwi 2019, 22:02:14 by Hibernate Tools 4.3.1



/**
 * Nauczyciel generated by hbm2java
 */
public class Nauczyciel  implements java.io.Serializable {


     private int pesel;
     private String nazwaKlasy;
     private String imie;
     private String nazwisko;
     private Boolean czyDyrektor;

    public Nauczyciel() {
    }

	
    public Nauczyciel(int pesel) {
        this.pesel = pesel;
    }
    public Nauczyciel(int pesel, String nazwaKlasy, String imie, String nazwisko, Boolean czyDyrektor) {
       this.pesel = pesel;
       this.nazwaKlasy = nazwaKlasy;
       this.imie = imie;
       this.nazwisko = nazwisko;
       this.czyDyrektor = czyDyrektor;
    }
   
    public int getPesel() {
        return this.pesel;
    }
    
    public void setPesel(int pesel) {
        this.pesel = pesel;
    }
    public String getNazwaKlasy() {
        return this.nazwaKlasy;
    }
    
    public void setNazwaKlasy(String nazwaKlasy) {
        this.nazwaKlasy = nazwaKlasy;
    }
    public String getImie() {
        return this.imie;
    }
    
    public void setImie(String imie) {
        this.imie = imie;
    }
    public String getNazwisko() {
        return this.nazwisko;
    }
    
    public void setNazwisko(String nazwisko) {
        this.nazwisko = nazwisko;
    }
    public Boolean getCzyDyrektor() {
        return this.czyDyrektor;
    }
    
    public void setCzyDyrektor(Boolean czyDyrektor) {
        this.czyDyrektor = czyDyrektor;
    }




}


