package mapping;
// Generated 20 kwi 2019, 14:16:52 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Obecnosc generated by hbm2java
 */
public class Obecnosc  implements java.io.Serializable {


     private Long id;
     private PrzedmiotPomocnicza przedmiotPomocnicza;
     private Uczen uczen;
     private Date data;
     private Boolean wartosc;

    public Obecnosc() {
    }

    public Obecnosc(PrzedmiotPomocnicza przedmiotPomocnicza, Uczen uczen, Date data, Boolean wartosc) {
       this.przedmiotPomocnicza = przedmiotPomocnicza;
       this.uczen = uczen;
       this.data = data;
       this.wartosc = wartosc;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public PrzedmiotPomocnicza getPrzedmiotPomocnicza() {
        return this.przedmiotPomocnicza;
    }
    
    public void setPrzedmiotPomocnicza(PrzedmiotPomocnicza przedmiotPomocnicza) {
        this.przedmiotPomocnicza = przedmiotPomocnicza;
    }
    public Uczen getUczen() {
        return this.uczen;
    }
    
    public void setUczen(Uczen uczen) {
        this.uczen = uczen;
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }
    public Boolean getWartosc() {
        return this.wartosc;
    }
    
    public void setWartosc(Boolean wartosc) {
        this.wartosc = wartosc;
    }




}


