package mapping;

// Generated 25 kwi 2019, 13:51:48 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Obecnosc generated by hbm2java
 */
public class Obecnosc  implements java.io.Serializable {


     private Long id;
     private Przedmiot przedmiot;
     private Uczen uczen;
     private Date data;
     private Boolean wartosc;

    public Obecnosc() {
    }

    public Obecnosc(Przedmiot przedmiot, Uczen uczen, Date data, Boolean wartosc) {
       this.przedmiot = przedmiot;
       this.uczen = uczen;
       this.data = data;
       this.wartosc = wartosc;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Przedmiot getPrzedmiot() {
        return this.przedmiot;
    }
    
    public void setPrzedmiot(Przedmiot przedmiot) {
        this.przedmiot = przedmiot;
    }
    public Uczen getUczen() {
        return this.uczen;
    }
    
    public void setUczen(Uczen uczen) {
        this.uczen = uczen;
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }
    public Boolean getWartosc() {
        return this.wartosc;
    }
    
    public void setWartosc(Boolean wartosc) {
        this.wartosc = wartosc;
    }




}


