package mapping;
// Generated 16 kwi 2019, 17:34:42 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import org.hibernate.annotations.GenericGenerator;

/**
 * Obecnosc generated by hbm2java
 */
public class Obecnosc  implements java.io.Serializable {
//do sprawdzenia - nie dziala

     private Long id;
     private Long pesel;
     private Date data;
     private Boolean wartosc;
     private String przedmiot;

@Id
@GenericGenerator(name="kaugen" , strategy="increment")
@GeneratedValue(generator="kaugen")
@Column(name="id")
  public Long getId() {
    return id;
 }


    public void setId(Long id) {
        this.id = id;
    }
     
     
    public Obecnosc() {
    }
//do wywalenia ten konstruktor
    public Obecnosc(Long pesel, Date data, Boolean wartosc, String przedmiot) {
        this.id = id;
        this.pesel = pesel;
        this.data = data;
        this.wartosc = wartosc;
        this.przedmiot = przedmiot;
    }



 

    public String getPrzedmiot() {
        return przedmiot;
    }

    public void setPrzedmiot(String przedmiot) {
        this.przedmiot = przedmiot;
    }

	

   
    public long getPesel() {
        return this.pesel;
    }
    
    public void setPesel(Long pesel) {
        this.pesel = pesel;
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }
    public Boolean getWartosc() {
        return this.wartosc;
    }
    
    public void setWartosc(Boolean wartosc) {
        this.wartosc = wartosc;
    }




}


