package mapping;
// Generated 6 kwi 2019, 17:33:07 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Ocena generated by hbm2java
 */
public class Ocena  implements java.io.Serializable {


     private int pesel;
     private String przedmiot;
     private String stopien;
     private Date data;
     private String opis;

    public Ocena() {
    }

	
    public Ocena(int pesel) {
        this.pesel = pesel;
    }
    public Ocena(int pesel, String przedmiot, String stopien, Date data, String opis) {
       this.pesel = pesel;
       this.przedmiot = przedmiot;
       this.stopien = stopien;
       this.data = data;
       this.opis = opis;
    }
   
    public int getPesel() {
        return this.pesel;
    }
    
    public void setPesel(int pesel) {
        this.pesel = pesel;
    }
    public String getPrzedmiot() {
        return this.przedmiot;
    }
    
    public void setPrzedmiot(String przedmiot) {
        this.przedmiot = przedmiot;
    }
    public String getStopien() {
        return this.stopien;
    }
    
    public void setStopien(String stopien) {
        this.stopien = stopien;
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }
    public String getOpis() {
        return this.opis;
    }
    
    public void setOpis(String opis) {
        this.opis = opis;
    }




}


