package mapping;
// Generated 21 kwi 2019, 11:03:06 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Ocena generated by hbm2java
 */
public class Ocena  implements java.io.Serializable {


     private Integer id;
     private Uczen uczen;
     private Long przedmiot;
     private String stopien;
     private Date data;
     private String opis;

    public Ocena() {
    }

	
    public Ocena(Uczen uczen) {
        this.uczen = uczen;
    }
    public Ocena(Uczen uczen, Long przedmiot, String stopien, Date data, String opis) {
       this.uczen = uczen;
       this.przedmiot = przedmiot;
       this.stopien = stopien;
       this.data = data;
       this.opis = opis;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Uczen getUczen() {
        return this.uczen;
    }
    
    public void setUczen(Uczen uczen) {
        this.uczen = uczen;
    }
    public Long getPrzedmiot() {
        return this.przedmiot;
    }
    
    public void setPrzedmiot(Long przedmiot) {
        this.przedmiot = przedmiot;
    }
    public String getStopien() {
        return this.stopien;
    }
    
    public void setStopien(String stopien) {
        this.stopien = stopien;
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }
    public String getOpis() {
        return this.opis;
    }
    
    public void setOpis(String opis) {
        this.opis = opis;
    }




}


