package mapping;
// Generated 20 kwi 2019, 14:16:52 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Ocena generated by hbm2java
 */
public class Ocena  implements java.io.Serializable {


     private Integer id;
     private PrzedmiotPomocnicza przedmiotPomocnicza;
     private Uczen uczen;
     private String stopien;
     private Date data;
     private String opis;

    public Ocena() {
    }

	
    public Ocena(Uczen uczen) {
        this.uczen = uczen;
    }
    public Ocena(PrzedmiotPomocnicza przedmiotPomocnicza, Uczen uczen, String stopien, Date data, String opis) {
       this.przedmiotPomocnicza = przedmiotPomocnicza;
       this.uczen = uczen;
       this.stopien = stopien;
       this.data = data;
       this.opis = opis;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public PrzedmiotPomocnicza getPrzedmiotPomocnicza() {
        return this.przedmiotPomocnicza;
    }
    
    public void setPrzedmiotPomocnicza(PrzedmiotPomocnicza przedmiotPomocnicza) {
        this.przedmiotPomocnicza = przedmiotPomocnicza;
    }
    public Uczen getUczen() {
        return this.uczen;
    }
    
    public void setUczen(Uczen uczen) {
        this.uczen = uczen;
    }
    public String getStopien() {
        return this.stopien;
    }
    
    public void setStopien(String stopien) {
        this.stopien = stopien;
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }
    public String getOpis() {
        return this.opis;
    }
    
    public void setOpis(String opis) {
        this.opis = opis;
    }




}


