package mapping;
// Generated 20 kwi 2019, 14:16:52 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Przedmiot generated by hbm2java
 */
public class Przedmiot  implements java.io.Serializable {


     private String nazwaPrzedmiotu;
     private Set przedmiotPomocniczas = new HashSet(0);

    public Przedmiot() {
    }

	
    public Przedmiot(String nazwaPrzedmiotu) {
        this.nazwaPrzedmiotu = nazwaPrzedmiotu;
    }
    public Przedmiot(String nazwaPrzedmiotu, Set przedmiotPomocniczas) {
       this.nazwaPrzedmiotu = nazwaPrzedmiotu;
       this.przedmiotPomocniczas = przedmiotPomocniczas;
    }
   
    public String getNazwaPrzedmiotu() {
        return this.nazwaPrzedmiotu;
    }
    
    public void setNazwaPrzedmiotu(String nazwaPrzedmiotu) {
        this.nazwaPrzedmiotu = nazwaPrzedmiotu;
    }
    public Set getPrzedmiotPomocniczas() {
        return this.przedmiotPomocniczas;
    }
    
    public void setPrzedmiotPomocniczas(Set przedmiotPomocniczas) {
        this.przedmiotPomocniczas = przedmiotPomocniczas;
    }




}


