package mapping;
// Generated 21 kwi 2019, 11:03:06 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Przedmiot generated by hbm2java
 */
public class Przedmiot  implements java.io.Serializable {


     private String nazwaPrzedmiotu;
     private Set zajecias = new HashSet(0);

    public Przedmiot() {
    }

	
    public Przedmiot(String nazwaPrzedmiotu) {
        this.nazwaPrzedmiotu = nazwaPrzedmiotu;
    }
    public Przedmiot(String nazwaPrzedmiotu, Set zajecias) {
       this.nazwaPrzedmiotu = nazwaPrzedmiotu;
       this.zajecias = zajecias;
    }
   
    public String getNazwaPrzedmiotu() {
        return this.nazwaPrzedmiotu;
    }
    
    public void setNazwaPrzedmiotu(String nazwaPrzedmiotu) {
        this.nazwaPrzedmiotu = nazwaPrzedmiotu;
    }
    public Set getZajecias() {
        return this.zajecias;
    }
    
    public void setZajecias(Set zajecias) {
        this.zajecias = zajecias;
    }




}


