package mapping;
// Generated 20 kwi 2019, 14:16:52 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * PrzedmiotPomocnicza generated by hbm2java
 */
public class PrzedmiotPomocnicza  implements java.io.Serializable {


     private long id;
     private Nauczyciel nauczyciel;
     private Przedmiot przedmiot;
     private Set ocenas = new HashSet(0);
     private Set obecnoscs = new HashSet(0);

    public PrzedmiotPomocnicza() {
    }

	
    public PrzedmiotPomocnicza(long id, Nauczyciel nauczyciel, Przedmiot przedmiot) {
        this.id = id;
        this.nauczyciel = nauczyciel;
        this.przedmiot = przedmiot;
    }
    public PrzedmiotPomocnicza(long id, Nauczyciel nauczyciel, Przedmiot przedmiot, Set ocenas, Set obecnoscs) {
       this.id = id;
       this.nauczyciel = nauczyciel;
       this.przedmiot = przedmiot;
       this.ocenas = ocenas;
       this.obecnoscs = obecnoscs;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public Nauczyciel getNauczyciel() {
        return this.nauczyciel;
    }
    
    public void setNauczyciel(Nauczyciel nauczyciel) {
        this.nauczyciel = nauczyciel;
    }
    public Przedmiot getPrzedmiot() {
        return this.przedmiot;
    }
    
    public void setPrzedmiot(Przedmiot przedmiot) {
        this.przedmiot = przedmiot;
    }
    public Set getOcenas() {
        return this.ocenas;
    }
    
    public void setOcenas(Set ocenas) {
        this.ocenas = ocenas;
    }
    public Set getObecnoscs() {
        return this.obecnoscs;
    }
    
    public void setObecnoscs(Set obecnoscs) {
        this.obecnoscs = obecnoscs;
    }




}


