package mapping;
// Generated 16 kwi 2019, 17:34:42 by Hibernate Tools 4.3.1



/**
 * PrzedmiotPomocnicza generated by hbm2java
 */
public class PrzedmiotPomocnicza  implements java.io.Serializable {


     private long id;
     private String nazwaPrzedmiotu;
     private String prowadzacy;

    public PrzedmiotPomocnicza() {
    }

    public PrzedmiotPomocnicza(long id, String nazwaPrzedmiotu, String prowadzacy) {
       this.id = id;
       this.nazwaPrzedmiotu = nazwaPrzedmiotu;
       this.prowadzacy = prowadzacy;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getNazwaPrzedmiotu() {
        return this.nazwaPrzedmiotu;
    }
    
    public void setNazwaPrzedmiotu(String nazwaPrzedmiotu) {
        this.nazwaPrzedmiotu = nazwaPrzedmiotu;
    }
    public String getProwadzacy() {
        return this.prowadzacy;
    }
    
    public void setProwadzacy(String prowadzacy) {
        this.prowadzacy = prowadzacy;
    }




}


