package mapping;
// Generated 21 kwi 2019, 11:03:06 by Hibernate Tools 4.3.1



/**
 * Rodzic generated by hbm2java
 */
public class Rodzic  implements java.io.Serializable {


     private long pesel;
     private Uczen uczen;
     private String imieOjca;
     private String nazwiskoOjca;
     private String imieMatki;
     private String nazwiskoMatki;

    public Rodzic() {
    }

	
    public Rodzic(long pesel) {
        this.pesel = pesel;
    }
    public Rodzic(long pesel, Uczen uczen, String imieOjca, String nazwiskoOjca, String imieMatki, String nazwiskoMatki) {
       this.pesel = pesel;
       this.uczen = uczen;
       this.imieOjca = imieOjca;
       this.nazwiskoOjca = nazwiskoOjca;
       this.imieMatki = imieMatki;
       this.nazwiskoMatki = nazwiskoMatki;
    }
   
    public long getPesel() {
        return this.pesel;
    }
    
    public void setPesel(long pesel) {
        this.pesel = pesel;
    }
    public Uczen getUczen() {
        return this.uczen;
    }
    
    public void setUczen(Uczen uczen) {
        this.uczen = uczen;
    }
    public String getImieOjca() {
        return this.imieOjca;
    }
    
    public void setImieOjca(String imieOjca) {
        this.imieOjca = imieOjca;
    }
    public String getNazwiskoOjca() {
        return this.nazwiskoOjca;
    }
    
    public void setNazwiskoOjca(String nazwiskoOjca) {
        this.nazwiskoOjca = nazwiskoOjca;
    }
    public String getImieMatki() {
        return this.imieMatki;
    }
    
    public void setImieMatki(String imieMatki) {
        this.imieMatki = imieMatki;
    }
    public String getNazwiskoMatki() {
        return this.nazwiskoMatki;
    }
    
    public void setNazwiskoMatki(String nazwiskoMatki) {
        this.nazwiskoMatki = nazwiskoMatki;
    }




}


