package mapping;
// Generated 9 maj 2019, 12:00:04 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * RodzajOceny generated by hbm2java
 */
public class RodzajOceny  implements java.io.Serializable {


     private String rodzajOceny;
     private Set ocenas = new HashSet(0);

    public RodzajOceny() {
    }

	
    public RodzajOceny(String rodzajOceny) {
        this.rodzajOceny = rodzajOceny;
    }
    public RodzajOceny(String rodzajOceny, Set ocenas) {
       this.rodzajOceny = rodzajOceny;
       this.ocenas = ocenas;
    }
   
    public String getRodzajOceny() {
        return this.rodzajOceny;
    }
    
    public void setRodzajOceny(String rodzajOceny) {
        this.rodzajOceny = rodzajOceny;
    }
    public Set getOcenas() {
        return this.ocenas;
    }
    
    public void setOcenas(Set ocenas) {
        this.ocenas = ocenas;
    }




}


