package mapping;
// Generated 9 maj 2019, 12:00:04 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Rodzic generated by hbm2java
 */
public class Rodzic  implements java.io.Serializable {


     private long pesel;
     private Autoryzacja autoryzacja;
     private String imieOjca;
     private String nazwiskoOjca;
     private String imieMatki;
     private String nazwiskoMatki;
     private Set uczens = new HashSet(0);

    public Rodzic() {
    }

	
    public Rodzic(Autoryzacja autoryzacja) {
        this.autoryzacja = autoryzacja;
    }
    public Rodzic(Autoryzacja autoryzacja, String imieOjca, String nazwiskoOjca, String imieMatki, String nazwiskoMatki, Set uczens) {
       this.autoryzacja = autoryzacja;
       this.imieOjca = imieOjca;
       this.nazwiskoOjca = nazwiskoOjca;
       this.imieMatki = imieMatki;
       this.nazwiskoMatki = nazwiskoMatki;
       this.uczens = uczens;
    }
   
    public long getPesel() {
        return this.pesel;
    }
    
    public void setPesel(long pesel) {
        this.pesel = pesel;
    }
    public Autoryzacja getAutoryzacja() {
        return this.autoryzacja;
    }
    
    public void setAutoryzacja(Autoryzacja autoryzacja) {
        this.autoryzacja = autoryzacja;
    }
    public String getImieOjca() {
        return this.imieOjca;
    }
    
    public void setImieOjca(String imieOjca) {
        this.imieOjca = imieOjca;
    }
    public String getNazwiskoOjca() {
        return this.nazwiskoOjca;
    }
    
    public void setNazwiskoOjca(String nazwiskoOjca) {
        this.nazwiskoOjca = nazwiskoOjca;
    }
    public String getImieMatki() {
        return this.imieMatki;
    }
    
    public void setImieMatki(String imieMatki) {
        this.imieMatki = imieMatki;
    }
    public String getNazwiskoMatki() {
        return this.nazwiskoMatki;
    }
    
    public void setNazwiskoMatki(String nazwiskoMatki) {
        this.nazwiskoMatki = nazwiskoMatki;
    }
    public Set getUczens() {
        return this.uczens;
    }
    
    public void setUczens(Set uczens) {
        this.uczens = uczens;
    }




}


