package mapping;
// Generated 9 maj 2019, 12:00:04 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Uczen generated by hbm2java
 */
public class Uczen  implements java.io.Serializable {


     private long pesel;
     private Autoryzacja autoryzacja;
     private Klasa klasa;
     private Rodzic rodzic;
     private String imie;
     private String nazwisko;
     private Set ocenas = new HashSet(0);
     private Set obecnoscs = new HashSet(0);
     private Set skladKlasies = new HashSet(0);

    public Uczen() {
    }

	
    public Uczen(Autoryzacja autoryzacja, Rodzic rodzic) {
        this.autoryzacja = autoryzacja;
        this.rodzic = rodzic;
    }
    public Uczen(Autoryzacja autoryzacja, Klasa klasa, Rodzic rodzic, String imie, String nazwisko, Set ocenas, Set obecnoscs, Set skladKlasies) {
       this.autoryzacja = autoryzacja;
       this.klasa = klasa;
       this.rodzic = rodzic;
       this.imie = imie;
       this.nazwisko = nazwisko;
       this.ocenas = ocenas;
       this.obecnoscs = obecnoscs;
       this.skladKlasies = skladKlasies;
    }
   
    public long getPesel() {
        return this.pesel;
    }
    
    public void setPesel(long pesel) {
        this.pesel = pesel;
    }
    public Autoryzacja getAutoryzacja() {
        return this.autoryzacja;
    }
    
    public void setAutoryzacja(Autoryzacja autoryzacja) {
        this.autoryzacja = autoryzacja;
    }
    public Klasa getKlasa() {
        return this.klasa;
    }
    
    public void setKlasa(Klasa klasa) {
        this.klasa = klasa;
    }
    public Rodzic getRodzic() {
        return this.rodzic;
    }
    
    public void setRodzic(Rodzic rodzic) {
        this.rodzic = rodzic;
    }
    public String getImie() {
        return this.imie;
    }
    
    public void setImie(String imie) {
        this.imie = imie;
    }
    public String getNazwisko() {
        return this.nazwisko;
    }
    
    public void setNazwisko(String nazwisko) {
        this.nazwisko = nazwisko;
    }
    public Set getOcenas() {
        return this.ocenas;
    }
    
    public void setOcenas(Set ocenas) {
        this.ocenas = ocenas;
    }
    public Set getObecnoscs() {
        return this.obecnoscs;
    }
    
    public void setObecnoscs(Set obecnoscs) {
        this.obecnoscs = obecnoscs;
    }
    public Set getSkladKlasies() {
        return this.skladKlasies;
    }
    
    public void setSkladKlasies(Set skladKlasies) {
        this.skladKlasies = skladKlasies;
    }




}


